name: BetterLottery-Reloaded
version: ${project.version}
main: cn.xtuly.mcp.betterlotteryreloaded.BetterLotteryReloaded
api-version: '1.20'
authors: [AmemiyaSigure,DoraLY,LDS_XiaoYe]
description: A reloaded version of BetterLottery
website: xtuly.cn
commands:
  bl:
    permission: bl.admin
permissions:
  bl.use:
    default: not op
  bl.admin:
    default: op